import Head from "next/head"
import { Header, Body, Button } from "@components"
export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header preset="h1">tes</Header>
            <Body preset="p1" className="">
                hello lorem ipsum
            </Body>

            <Button preset="primary">hello lorem ipsum</Button>
        </>
    )
}
