import Head from "next/head"
import { Header, Body, Button } from "@components"
import { useToast } from "@chakra-ui/react"
export default function Home() {
    const toast = useToast()
    // const successToast = Toast({
    //     preset: "success",
    //     message: "Berhasil login",
    // })
    // const errorToast = Toast({
    //     preset: "error",
    //     message: "Akun tidak ditemukan. Pastikan username dan password benar",
    // })
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header preset="h1">tes</Header>
            <Body preset="p1" className="">
                hello lorem ipsum
            </Body>
            <div>e</div>
            <Button
                preset="primary"
                onClick={() =>
                    toast({
                        title: "Account created.",
                        description: "We've created your account for you.",
                        status: "success",
                        duration: 9000,
                        isClosable: true,
                    })
                }
            >
                hello lorem ipsum
            </Button>
        </>
    )
}
